export const Users = [
    {
      id:1,
      profilePicture: "assets/people/athete.jpg",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "assets/people/biking.jpeg",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "assets/people/headphones.jpeg",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "assets/people/person.jpeg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "assets/people/womanbiking.jpeg",
      username: "Thomas Holden",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];