export const Users = [
  {
    id:1,
    profilePicture: "assets/people/womansunset.jpeg",
    username: "Sam Jackson",
  },
  {
    id:2,
    profilePicture: "assets/people/biking.jpeg",
    username: "Randi Shrum",
  },
  {
    id:3,
    profilePicture: "assets/people/headphones.jpeg",
    username: "Alex Durden",
  },
  {
    id:4,
    profilePicture: "assets/people/person.jpeg",
    username: "Avery Hawks",
  },
  {
    id:5,
    profilePicture: "assets/people/womanbiking.jpeg",
    username: "Taylor Holden",
  },
  {
    id:6,
    profilePicture: "assets/people/womansmiling.jpeg",
    username: "Jamie Beauchamp",
  },
  {
    id:7,
    profilePicture: "assets/people/mountain.jpeg",
    username: "Frankie Bennett",
  },
  {
    id:8,
    profilePicture: "assets/people/manandkid.jpeg",
    username: "Billie Thomas",
  },
  {
    id:9,
    profilePicture: "assets/people/womanyoga.jpeg",
    username: "Cameron Duty",
  },
  {
    id:10,
    profilePicture: "assets/people/athlete.jpg",
    username: "Riley Owens",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Getting some fresh air :)",
    photo: "assets/people/womansunset.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/people/biking.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/people/headphones.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/people/person.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/people/womanbiking.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/people/womansmiling.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/people/mountain.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/people/manandkid.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/people/womanyoga.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/people/athlete.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];